### ISSUE TITLE
Vector_file causes issues with duplicate keys

### ISSUE THREAD

**Issue by organisciak** [bmschmidt/pySRP#8]
There is no name checking to prevent duplicate keys, and they can be iterated over without issue. However, this subsequently causes issues in `build_offset_lookup`, because this loop never satisfies: https://github.com/bmschmidt/pySRP/blob/febf7320284eb0ae69c897b4ccc2e3f92a6ab683/SRP/SRP_files.py#L389.

For now, commit aebb39342 raises an error rather than allowing an infinite loop.

**Comment by bmschmidt** [comment]
The looping is now handled in a safer way, and the code throws a warning if it notices duplicate keys.

https://github.com/bmschmidt/pySRP/commit/ce26a919d62d6404ac6c7a0ce7dc44ac8ab313a4
